/* JS */ gapi.loaded_0(function(_){var window=this;
_.m=function(a){throw a;};_.p=void 0;_.r=!0;_.s=null;_.u=!1;_.aa=function(){return function(a){return a}};_.x=function(){return function(){}};_.ba=function(a){return function(c){this[a]=c}};_.y=function(a){return function(){return this[a]}};_.ca=function(a){return function(){return a}};_.D=function(a,c,f){a=a.split(".");f=f||_.E;!(a[0]in f)&&f.execScript&&f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&(0,_.G)(c)?f[g]=c:f=f[g]?f[g]:f[g]={}};
_.da=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof window.Array)return"array";if(a instanceof window.Object)return c;var f=window.Object.prototype.toString.call(a);if("[object Window]"==f)return"object";if("[object Array]"==f||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==f||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};_.G=function(a){return a!==_.p};_.ea=function(a){return"array"==(0,_.da)(a)};_.fa=function(a){return"string"==typeof a};_.ga=function(a){return"function"==(0,_.da)(a)};_.ha=function(a){var c=typeof a;return"object"==c&&a!=_.s||"function"==c};_.ia=function(a,c,f){return a.call.apply(a.bind,arguments)};
_.la=function(a,c,f){a||(0,_.m)((0,window.Error)());if(2<arguments.length){var g=window.Array.prototype.slice.call(arguments,2);return function(){var f=window.Array.prototype.slice.call(arguments);window.Array.prototype.unshift.apply(f,g);return a.apply(c,f)}}return function(){return a.apply(c,arguments)}};_.H=function(a,c,f){_.H=window.Function.prototype.bind&&-1!=window.Function.prototype.bind.toString().indexOf("native code")?_.ia:_.la;return _.H.apply(_.s,arguments)};
_.ma=function(a,c){var f=window.Array.prototype.slice.call(arguments,1);return function(){var c=window.Array.prototype.slice.call(arguments);c.unshift.apply(c,f);return a.apply(this,c)}};_.J=function(a,c){function f(){}f.prototype=c.prototype;a.v=c.prototype;a.prototype=new f;a.prototype.constructor=a};_._DumpException=function(a){(0,_.m)(a)};_.na=_.na||{};_.E=this;_.oa="closure_uid_"+window.Math.floor(2147483648*window.Math.random()).toString(36);_.pa=window.Date.now||function(){return+new window.Date}; window.Function.prototype.bind=window.Function.prototype.bind||function(a,c){if(1<arguments.length){var f=window.Array.prototype.slice.call(arguments,1);f.unshift(this,a);return _.H.apply(_.s,f)}return(0,_.H)(this,a)};
_.qa=window.gapi||{};_.ra=window.gadgets||{};_.L=window.osapi=window.osapi||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:_.u},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.u},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.u},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/u/:session_index:/_/pages/badge"},":socialhost:":"https://plusone.google.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton"},
plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator"},appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"chili.people.list":_.r,"pos.plusones.list":_.r,"pos.plusones.get":_.r,"chili.people.get":_.r,
"pos.plusones.insert":_.r,"chili.activities.list":_.r,"pos.plusones.delete":_.r,"chili.activities.get":_.r,"chili.activities.search":_.r,"pos.plusones.getSignupState":_.r},requestCache:{enabled:_.r},versions:{chili:"v1",pos:"v1"},rpc:"/rpc",root:"https://www.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:_.r},transport:{isProxyShared:_.r},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:_.u}},drive_saver:{driveUrl:"https://drive.google.com"}});

window.___jsl=window.___jsl||{};(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"onload"},iframes:{":source:":"3p"}});
_.ta=function(a,c,f){return a[c]=a[c]||f};_.N=function(){var a;if((a=window.Object.create)&&_.ua.test(a))a=a(_.s);else{a={};for(var c in a)a[c]=_.p}return a};_.va=function(a,c){var f=a.createElement("div"),g=a.createElement("a");g.href=c;f.appendChild(g);f.innerHTML=f.innerHTML;c=(0,window.String)(f.firstChild.href);f.parentNode&&f.parentNode.removeChild(f);return c};_.wa=function(){return(0,_.ta)(_.xa,"WI",(0,_.N)())};_.ya=function(){return _.xa.ssfn};
_.za=function(a){var c=window.___jsl=window.___jsl||{};c[a]=c[a]||[];return c[a]};_.Aa=function(a){var c=window.___jsl=window.___jsl||{};c.cfg=!a&&c.cfg||{};return c.cfg};_.Ba=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
_.Da=function(a,c){if(c)for(var f in c)c.hasOwnProperty(f)&&(a[f]&&c[f]&&"object"===typeof a[f]&&"object"===typeof c[f]&&!(0,_.Ba)(a[f])&&!(0,_.Ba)(c[f])?(0,_.Da)(a[f],c[f]):c[f]&&"object"===typeof c[f]?(a[f]=(0,_.Ba)(c[f])?[]:{},(0,_.Da)(a[f],c[f])):a[f]=c[f])};
_.Ea=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var c;try{c=window.JSON.parse(a)}catch(f){}if("object"===typeof c)return c;try{c=(new window.Function("return ("+a+"\n)"))()}catch(g){}if("object"===typeof c)return c;try{c=(new window.Function("return ({"+a+"\n})"))()}catch(h){}return"object"===typeof c?c:{}}};
_.Fa=function(a){(0,_.Aa)(_.r);var c=window.___gcfg,f=(0,_.za)("cu");if(c&&c!==window.___gu){var g={};(0,_.Da)(g,c);f.push(g);window.___gu=c}var c=(0,_.za)("cu"),h=window.document.scripts||window.document.getElementsByTagName("script")||[],g=[],l=[];l.push.apply(l,(0,_.za)("us"));for(var n=0;n<h.length;++n)for(var q=h[n],t=0;t<l.length;++t)q.src&&0==q.src.indexOf(l[t])&&g.push(q);0==g.length&&(0<h.length&&h[h.length-1].src)&&g.push(h[h.length-1]);for(h=0;h<g.length;++h)g[h].getAttribute("gapi_processed")||
(g[h].setAttribute("gapi_processed",_.r),(l=g[h])?(n=l.nodeType,l=3==n||4==n?l.nodeValue:l.textContent||l.innerText||l.innerHTML||""):l=_.p,(l=(0,_.Ea)(l))&&c.push(l));a&&(g={},(0,_.Da)(g,a),f.push(g));g=(0,_.za)("cd");a=0;for(c=g.length;a<c;++a)(0,_.Da)((0,_.Aa)(),g[a]);g=(0,_.za)("ci");a=0;for(c=g.length;a<c;++a)(0,_.Da)((0,_.Aa)(),g[a]);a=0;for(c=f.length;a<c;++a)(0,_.Da)((0,_.Aa)(),f[a])};
_.O=function(a,c){if(!a)return(0,_.Aa)();for(var f=a.split("/"),g=(0,_.Aa)(),h=0,l=f.length;g&&"object"===typeof g&&h<l;++h)g=g[f[h]];return h===f.length&&g!==_.p?g:c};_.Ga=function(a,c){var f=a;if("string"===typeof a){for(var g=f={},h=a.split("/"),l=0,n=h.length;l<n-1;++l)var q={},g=g[h[l]]=q;g[h[l]]=c}(0,_.Fa)(f)};_.Ha=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),(0,_.ta)(_.xa,"ci",[]).push(a),window.__GOOGLEAPIS=_.p)}; _.P=function(a,c){c="function"==typeof _.Ia&&(0,_.Ia)(a,c)||c;(0,_.D)(a,c,_.p)};
_.Ja=window;_.Ka=window.document;_.ua=/\[native code\]/;_.La=(0,_.ta)(_.Ja,"gapi",{});_.xa=(0,_.ta)(_.Ja,"___jsl",(0,_.N)());(0,_.ta)(_.xa,"I",0);(0,_.ta)(_.xa,"hel",10);_.Ha&&(0,_.Ha)();(0,_.Fa)();(0,_.P)("gapi.config.get",_.O);(0,_.P)("gapi.config.update",_.Ga);

_.Ra=function(a,c){return window.Object.prototype.hasOwnProperty.call(a,c)};_.Sa=function(a,c){a=a||{};for(var f in a)(0,_.Ra)(a,f)&&(c[f]=a[f])};_.Ua=function(a,c,f,g,h){if(a[g+"EventListener"])a[g+"EventListener"](c,f,_.u);else if(a[h+"tachEvent"])a[h+"tachEvent"]("on"+c,f)};_.Va=function(a,c,f){var g=(0,window.RegExp)("([#].*&|[#])"+c+"=([^&#]*)","g");c=(0,window.RegExp)("([?#].*&|[?#])"+c+"=([^&#]*)","g");if(a=a&&(g.exec(a)||c.exec(a)))try{f=(0,window.decodeURIComponent)(a[2])}catch(h){}return f}; _.Wa=function(a,c,f){(0,_.Ua)(a,c,f,"add","at")};

_.Xa={go:{},H:{}};_.$a={go:{},H:{}};


_.ab=function(a){var c=[];if(a)for(var f in a)(0,_.Ra)(a,f)&&a[f]!=_.s&&c.push((0,window.encodeURIComponent)(f)+"="+(0,window.encodeURIComponent)(a[f]));return c};_.bb=function(a){return a.yc+(0<a.mb.length?"?"+a.mb.join("&"):"")+(0<a.Vf.length?"#"+a.Vf.join("&"):"")};_.cb=function(a){a=a.match(_.db);var c=(0,_.N)();c.yc=a[1];c.mb=a[3]?[a[3]]:[];c.Vf=a[5]?[a[5]]:[];return c};_.eb=function(a,c,f){a=(0,_.cb)(a);a.mb.push.apply(a.mb,(0,_.ab)(c));a.Vf.push.apply(a.Vf,(0,_.ab)(f));return(0,_.bb)(a)};
_.fb=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.gb=function(a,c){a||(0,_.m)((0,window.Error)(c||""))};_.hb=function(a){return(0,window.String)(a).replace(_.ib,"&amp;").replace(_.jb,"&lt;").replace(_.kb,"&gt;").replace(_.lb,"&quot;").replace(_.mb,"&#39;")};_.nb=function(){var a=_.xa.onl;if(!a){a=(0,_.N)();_.xa.onl=a;var c=(0,_.N)();a.e=function(a){var g=c[a];g&&(delete c[a],g())};a.a=function(a,g){c[a]=g};a.r=function(a){delete c[a]}}return a};
_.ob=function(a,c){var f=c.onload;return"function"===typeof f?((0,_.nb)().a(a,f),f):_.s};_.pb=function(a){(0,_.gb)(/^\w+$/.test(a),"Unsupported id - "+a);(0,_.nb)();return'onload="window.___jsl.onl.e(&#34;'+a+'&#34;)"'};_.qb=function(a){(0,_.nb)().r(a)};
_.rb=function(a,c,f,g,h){var l,n=(0,_.ob)(g,f),q=n?(0,_.pb)(g):"";try{l=a.createElement('<iframe frameborder="'+(0,_.hb)(f.frameborder)+'" scrolling="'+(0,_.hb)(f.scrolling)+'" '+q+' name="'+(0,_.hb)(f.name)+'"/>')}catch(t){l=a.createElement("iframe"),n&&(l.onload=function(){l.onload=_.s;n.call(this)},(0,_.qb)(g))}for(var v in f)a=f[v],"style"===v&&"object"===typeof a?(0,_.Sa)(a,l.style):_.sb[v]||l.setAttribute(v,(0,window.String)(a));(!h||!h.dontclear)&&(0,_.fb)(c);c.appendChild(l);l=c.lastChild;
f.allowtransparency&&(l.allowTransparency=_.r);return l};_.tb=function(){return _.s};
_.ub=function(a,c,f){var g=f||{};f=g.attributes||{};(0,_.gb)(!g.allowPost||!f.onload,"onload is not supported by post iframe");!g.rpctoken&&!(0,_.Va)(a,"rpctoken")&&(g.rpctoken=(0,_.tb)());f=c.ownerDocument||_.Ka;var h,l=0;do h=g.id||["I",_.vb++,"_",(new window.Date).getTime()].join("");while(f.getElementById(h)&&5>++l);(0,_.gb)(5>l,"Error creating iframe id");var n,q=f.location.href,l=(0,_.N)(),t=(0,_.Va)(q,"_bsh",_.xa.bsh);t&&(l._bsh=t);(q=!_.xa.dpo?(0,_.Va)(q,"jsh",_.xa.h):_.xa.h)&&(l.jsh=q);q=
(0,_.N)();q.id=h;q.parent=f.location.protocol+"//"+f.location.host;var t=(0,_.Va)(f.location.href,"id",""),v=(0,_.Va)(f.location.href,"pfname","");(t=t?v+"/"+t:"")&&(q.pfname=t);g.rpctoken&&(q.rpctoken=g.rpctoken);g.hintInFragment?(0,_.Sa)(l,q):n=l;n=(0,_.eb)(a,n,q);a=(0,_.N)();(0,_.Sa)(_.wb,a);(0,_.Sa)(g.attributes,a);a.name=a.id=h;a.src=n;if((g||{}).allowPost&&2E3<n.length){n=(0,_.cb)(n);a.src="";a["data-postorigin"]=n.yc;a=(0,_.rb)(f,c,a,h);var w;-1!=window.navigator.userAgent.indexOf("WebKit")&&
(w=a.contentWindow.document,w.open(),l=w.createElement("div"),q={},t=h+"_inner",q.name=t,q.src="",q.style="display:none",(0,_.rb)(f,l,q,t,g));l=(g=n.mb[0])?g.split("&"):[];g=[];for(q=0;q<l.length;q++)t=l[q].split("=",2),g.push([(0,window.decodeURIComponent)(t[0]),(0,window.decodeURIComponent)(t[1])]);n.mb=[];l=(0,_.bb)(n);n=f.createElement("form");n.action=l;n.method="POST";n.target=h;n.style.display="none";for(h=0;h<g.length;h++)l=f.createElement("input"),l.type="hidden",l.name=g[h][0],l.value=g[h][1], n.appendChild(l);c.appendChild(n);n.submit();n.parentNode.removeChild(n);w&&w.close();c=a}else c=(0,_.rb)(f,c,a,h,g);return c};_.db=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/;_.mb=/'/g;_.lb=/"/g;_.kb=/>/g;_.jb=/</g;_.ib=/&/g;
_.wb={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};_.sb={allowtransparency:_.r,onload:_.r};_.vb=0;
_.Q=_.Q||{};
_.Q=_.Q||{};_.Q.Dg=function(a,c,f){for(var g=[],h=2,l=arguments.length;h<l;++h)g.push(arguments[h]);return function(){for(var f=g.slice(),h=0,l=arguments.length;h<l;++h)f.push(arguments[h]);return c.apply(a,f)}};_.Q.mf=function(a){var c,f,g={};for(c=0;f=a[c];++c)g[f]=f;return g};

_.Q=_.Q||{};
(function(){function a(a,c){return window.String.fromCharCode(c)}var c={"0":_.u,10:_.r,13:_.r,34:_.r,39:_.r,60:_.r,62:_.r,92:_.r,8232:_.r,8233:_.r,65282:_.r,65287:_.r,65308:_.r,65310:_.r,65340:_.r};_.Q.escape=function(a,c){if(a){if("string"===typeof a)return _.Q.Qf(a);if("array"===typeof a)for(var h=0,l=a.length;h<l;++h)a[h]=_.Q.escape(a[h]);else if("object"===typeof a&&c){h={};for(l in a)a.hasOwnProperty(l)&&(h[_.Q.Qf(l)]=_.Q.escape(a[l],_.r));return h}}return a};_.Q.Qf=function(a){if(!a)return a;for(var g= [],h,l,n=0,q=a.length;n<q;++n)h=a.charCodeAt(n),l=c[h],l===_.r?g.push("&#",h,";"):l!==_.u&&g.push(a.charAt(n));return g.join("")};_.Q.su=function(c){return!c?c:c.replace(/&#([0-9]+);/g,a)}})();

_.Pb=_.Pb||{};_.Pb.Xk=function(){var a=0,c=0;window.self.innerHeight?(a=window.self.innerWidth,c=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,c=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,c=window.document.body.clientHeight);return{width:a,height:c}};

_.Pb=_.Pb||{};
(function(){function a(a,f){window.getComputedStyle(a,"").getPropertyValue(f).match(/^([0-9]+)/);return(0,window.parseInt)(window.RegExp.$1,10)}_.Pb.ai=function(){var c=_.Pb.Xk().height,f=window.document.body,g=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&g.scrollHeight)return g.scrollHeight!==c?g.scrollHeight:g.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){c=0;for(f=[window.document.body];0<f.length;){var h=f.shift(),g=h.childNodes;if("undefined"!==
typeof h.style){var l=h.style.overflowY;l||(l=(l=window.document.defaultView.getComputedStyle(h,_.s))?l.overflowY:_.s);if("visible"!=l&&"inherit"!=l&&(l=h.style.height,l||(l=(l=window.document.defaultView.getComputedStyle(h,_.s))?l.height:""),0<l.length&&"auto"!=l))continue}for(h=0;h<g.length;h++){l=g[h];if("undefined"!==typeof l.offsetTop&&"undefined"!==typeof l.offsetHeight)var n=l.offsetTop+l.offsetHeight+a(l,"margin-bottom"),c=window.Math.max(c,n);f.push(l)}}return c+a(window.document.body,"border-bottom")+ a(window.document.body,"margin-bottom")+a(window.document.body,"padding-bottom")}if(f&&g)return h=g.scrollHeight,l=g.offsetHeight,g.clientHeight!==l&&(h=f.scrollHeight,l=f.offsetHeight),h>c?h>l?h:l:h<l?h:l}})();

_.Sb=window.gapi&&window.gapi.util||{};
_.Sb=_.Sb||{};_.Sb.wh=function(){var a={Oj:"bsh",Vj:"h"};window.___jsl=window.___jsl||{};return{b:function(){return window.___jsl[a.Oj]},Ok:function(){return window.___jsl[a.Vj]},qj:function(c){window.___jsl[a.Oj]=c},ys:function(c){window.___jsl[a.Vj]=c}}}();

if(window.JSON&&window.JSON.parse&&window.JSON.stringify)_.Lb=function(){function a(a){return this[a]}var c=/___$/;return{parse:function(a){try{return window.JSON.parse(a)}catch(c){return _.u}},stringify:function(f){function g(c){return h.call(this,c,a)}var h=window.JSON.stringify,l=window.Array.prototype.toJSON&&'"[{\\"x\\": 1}]"'===h([{x:1}])?g:h;try{return l(f,function(a,f){return!c.test(a)?f:_.p})}catch(n){return _.s}}}}();
if(!window.JSON||!window.JSON.parse||!window.JSON.stringify)_.Lb=function(){function a(a){return 10>a?"0"+a:a}function c(a){var h,l,n;h=/[\"\\\x00-\x1f\x7f-\x9f]/g;switch(typeof a){case "string":return h.test(a)?'"'+a.replace(h,function(a){var c=f[a];if(c)return c;c=a.charCodeAt();return"\\u00"+window.Math.floor(c/16).toString(16)+(c%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?(0,window.String)(a):"null";case "boolean":case "null":return(0,window.String)(a);case "object":if(!a)return"null";
h=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){n=a.length;for(l=0;l<n;l+=1)h.push(c(a[l])||"null");return"["+h.join(",")+"]"}for(l in a)!/___$/.test(l)&&a.hasOwnProperty(l)&&"string"===typeof l&&(n=c(a[l]))&&h.push(c(l)+":"+n);return"{"+h.join(",")+"}"}return""}window.Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",a(this.getUTCMonth()+1),"-",a(this.getUTCDate()),"T",a(this.getUTCHours()),":",a(this.getUTCMinutes()),":",a(this.getUTCSeconds()),"Z"].join("")};
var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:c,parse:function(a){return/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?eval("("+a+")"):_.u}}}();
_.Lb.Dk=function(a){var c={};if(a===_.s||a===_.p)return c;for(var f in a)if(a.hasOwnProperty(f)){var g=a[f];_.s===g||_.p===g||(c[f]="string"===typeof g?g:_.Lb.stringify(g))}return c};(0,_.P)("gadgets.json.flatten",_.Lb.Dk);(0,_.P)("gadgets.json.parse",_.Lb.parse);(0,_.P)("gadgets.json.stringify",_.Lb.stringify);(0,_.P)("gadgets.json.flatten",_.Lb.Dk);(0,_.P)("gadgets.json.parse",_.Lb.parse);(0,_.P)("gadgets.json.stringify",_.Lb.stringify);

_.Q=_.Q||{};(function(){var a=[];_.Q.du=function(c){a.push(c)};_.Q.ku=function(){for(var c=0,f=a.length;c<f;++c)a[c]()}})();
_.Ob=function(a){for(var c=0;c<this.length;c++)if(this[c]===a)return c;return-1};_.Q=_.Q||{};
(function(){var a=_.s;_.Q.na=function(c){var f="undefined"===typeof c;if(a!==_.s&&f)return a;var g={};c=c||window.document.location.href;var h=c.indexOf("?"),l=c.indexOf("#");c=(-1===l?c.substr(h+1):[c.substr(h+1,l-h-1),"&",c.substr(l+1)].join("")).split("&");for(var h=window.decodeURIComponent?window.decodeURIComponent:window.unescape,l=0,n=c.length;l<n;++l){var q=c[l].indexOf("=");if(-1!==q){var t=c[l].substring(0,q),q=c[l].substring(q+1),q=q.replace(/\+/g," ");try{g[t]=h(q)}catch(v){}}}f&&(a=g); return g};_.Q.na()})();
(0,_.P)("gadgets.util.getUrlParameters",_.Q.na);
_.Qb=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&(0,_.Ga)(a());return{R:function(a,f,g){g&&g((0,_.O)())},get:function(a){return(0,_.O)(a)},update:function(a,f){f&&(0,_.m)("Config replacement is not supported");(0,_.Ga)(a)},ba:(0,_.x)()}}();
(0,_.P)("gadgets.config.register",_.Qb.R);(0,_.P)("gadgets.config.get",_.Qb.get);(0,_.P)("gadgets.config.init",_.Qb.ba);(0,_.P)("gadgets.config.update",_.Qb.update);
_.Rb=_.Rb||{};_.Rb.Km=_.s;_.Rb.bm=_.s;_.Rb.pg=_.s;_.Rb.frameElement=_.s;_.Rb=_.Rb||{};
_.Rb.Mj||(_.Rb.Mj=function(){function a(a,c,f){"undefined"!=typeof window.addEventListener?window.addEventListener(a,c,f):"undefined"!=typeof window.attachEvent&&window.attachEvent("on"+a,c);"message"===a&&(window.___jsl=window.___jsl||{},a=window.___jsl,a.RPMQ=a.RPMQ||[],a.RPMQ.push(c))}function c(a){var c=_.Lb.parse(a.data);if(c&&c.f){var g=_.R.Yd(c.f);h&&("undefined"!==typeof a.origin?a.origin!==g:a.domain!==/^.+:\/\/([^:]+).*/.exec(g)[1])?(0,_.sa)("Invalid rpc message origin. "+g+" vs "+(a.origin||
"")):f(c,a.origin)}}var f,g,h=_.r;return{Lk:(0,_.ca)("wpm"),b:(0,_.ca)(_.r),ba:function(l,n){_.Qb.R("rpc",_.s,function(a){if("true"===(0,window.String)((a&&a.rpc||{}).disableForceSecure))h=_.u});f=l;g=n;a("message",c,_.u);g("..",_.r);return _.r},sf:function(a){g(a,_.r);return _.r},call:function(a,c,f){var g=_.R.Yd(a),h=_.R.ek(a);g?window.setTimeout(function(){h.postMessage(_.Lb.stringify(f),g)},0):".."!=a&&(0,_.sa)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return _.r}}}());
_.Rb=_.Rb||{};
_.Rb.Uf||(_.Rb.Uf=function(){function a(a,c){function f(){a.apply({},arguments)}Za[c]=Za[c]||f;return ja+"."+c}function c(){if(M===_.s&&window.document.body&&v){var a=v+"?cb="+window.Math.random()+"&origin="+Ca+"&jsl=1",f=window.document.createElement("div");f.style.height="1px";f.style.width="1px";a='<object height="1" width="1" id="'+t+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+a+
'" height="1" width="1"></embed></object>';window.document.body.appendChild(f);f.innerHTML=a;M=f.firstChild}++K;F!==_.s&&(M!==_.s||50<=K)?window.clearTimeout(F):F=window.setTimeout(c,100)}function f(){S[".."]||(q(".."),U++,50<=U&&ka!==_.s?(window.clearTimeout(ka),ka=_.s):ka=window.setTimeout(f,100))}function g(){if(M!==_.s&&M.setup)for(;0<I.length;){var a=I.shift(),c=a.Qs;M.setup(a.te,".."===c?_.R.kh:c,".."===c?"INNER":"OUTER")}F!==_.s&&window.clearTimeout(F);F=_.s}function h(){!S[".."]&&ka===_.s&&
(ka=window.setTimeout(f,100))}function l(a,c,f){c=_.R.Yd(a);var g=_.R.Ud(a);M["sendMessage_"+(".."===a?_.R.kh:a)+"_"+g+"_"+(".."===a?"INNER":"OUTER")].call(M,_.Lb.stringify(f),c);return _.r}function n(a,c){var f=_.Lb.parse(a),g=f._scr;g?(C(g,_.r),S[g]=_.r,".."!==g&&q(g,_.r)):window.setTimeout(function(){A(f,c)},0)}function q(a,c){var f=_.R.kh,g={};g._scr=c?"..":f;g._pnt=f;l(a,f,g)}var t="___xpcswf",v=_.s,w=_.u,A=_.s,C=_.s,M=_.s,I=[],F=_.s,K=0,U=0,ka=_.s,S={},Ca=window.location.protocol+"//"+window.location.host,
ja,Za=function(){window.___jsl=window.___jsl||{};var a=window.___jsl._fm={};ja="___jsl._fm";return a}();_.Qb.R("rpc",_.s,function(a){w&&(v=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});a(g,"ready");a(h,"setupDone");a(n,"receiveMessage");return{Lk:(0,_.ca)("flash"),b:(0,_.ca)(_.r),ba:function(a,c){A=a;C=c;return w=_.r},sf:function(a,f){I.push({te:f,Qs:a});M===_.s&&F===_.s&&(F=window.setTimeout(c,100));return _.r},call:l,Vo:n,d:g,i:h}}());
if(!window.gadgets||!window.gadgets.rpc){_.R=function(){function a(){}function c(a,c){if(!Ya[a]){var f=ec;c||(f=re);Ya[a]=f;for(var g=If[a]||[],h=0;h<g.length;++h){var l=g[h];l.t=S[a];f.call(a,l.f,l)}If[a]=[]}}function f(){function a(){Go=_.r}Ho||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,_.u):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),Ho=_.r)}function g(c,g,h,l,n){if(!S[g]||S[g]!==h)(0,_.sa)("Invalid gadgets.rpc token. "+S[g]+" vs "+
h),a(g,2);n.onunload=function(){Za[g]&&!Go&&(a(g,1),_.R.nj(g))};f();l=_.Lb.parse((0,window.decodeURIComponent)(l))}function h(f,g){if(f&&"string"===typeof f.s&&"string"===typeof f.f&&f.a instanceof window.Array)if(S[f.f]&&S[f.f]!==f.t&&((0,_.sa)("Invalid gadgets.rpc token. "+S[f.f]+" vs "+f.t),a(f.f,2)),"__ack"===f.s)window.setTimeout(function(){c(f.f,_.r)},0);else{f.c&&(f.callback=function(a){_.R.call(f.f,(f.g?"legacy__":"")+"__cb",_.s,f.c,a)});if(g){var h=l(g);f.origin=g;var n=f.r;if(!n||l(n)!=
h)n=g;f.referer=n}h=(K[f.s]||K[""]).apply(f,f.a);f.c&&"undefined"!==typeof h&&_.R.call(f.f,"__cb",_.s,f.c,h)}}function l(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));a=a.substring(0,a.indexOf("://"));var f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+1),c=c.substring(0,g);if("http"===
a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f}function n(a){if("/"==a.charAt(0)){var c=a.indexOf("|");return{id:0<c?a.substring(1,c):a.substring(1),origin:0<c?a.substring(c+1):_.s}}return _.s}function q(a){if("undefined"===typeof a||".."===a)return window.parent;var c=n(a);if(c)return window.top.frames[c.id];a=(0,window.String)(a);return(c=window.frames[a])?c:(c=window.document.getElementById(a))&&c.contentWindow?c.contentWindow:_.s}function t(a,c){if(Za[a]!==_.r){"undefined"===typeof Za[a]&&
(Za[a]=0);var f=q(a);(".."===a||f!=_.s)&&ec.sf(a,c)===_.r?Za[a]=_.r:Za[a]!==_.r&&10>Za[a]++?window.setTimeout(function(){t(a,c)},500):(Ya[a]=re,Za[a]=_.r)}}function v(a){(a=U[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function w(a,c,f){c&&!/http(s)?:\/\/.+/.test(c)&&(0==c.indexOf("//")?c=window.location.protocol+c:"/"==c.charAt(0)?c=window.location.protocol+"//"+window.location.host+
c:-1==c.indexOf("://")&&(c=window.location.protocol+"//"+c));U[a]=c;"undefined"!==typeof f&&(ka[a]=!!f)}function A(a,c){c=c||"";S[a]=(0,window.String)(c);t(a,c)}function C(a){a=(a.passReferrer||"").split(":",2);wh=a[0]||"none";nk=a[1]||"origin"}function M(a){"true"===(0,window.String)(a.useLegacyProtocol)&&(ec=_.Rb.pg||re,ec.ba(h,c))}function I(a,c){function f(g){g=g&&g.rpc||{};C(g);var h=g.parentRelayUrl||"",h=l(Ta.parent||c)+h;w("..",h,"true"===(0,window.String)(g.useLegacyProtocol));M(g);A("..",
a)}!Ta.parent&&c?f({}):_.Qb.R("rpc",_.s,f)}function F(a,c,f){if(".."===a)I(f||Ta.rpctoken||Ta.ifpctok||"",c);else a:{var g=_.s;if("/"!=a.charAt(0)){if(!_.Q)break a;(g=window.document.getElementById(a))||(0,_.m)((0,window.Error)("h`"+a))}g=g&&g.src;c=c||_.R.ka(g);w(a,c);c=_.Q.na(g);A(a,f||c.rpctoken)}}var K={},U={},ka={},S={},Ca=0,ja={},Za={},Ta={},Ya={},If={},wh=_.s,nk=_.s,Ww=window.top!==window.self,ok=window.name,pk=window.console,Io=pk&&pk.log&&function(a){pk.log(a)}||(0,_.x)(),re=function(){function a(c){return function(){Io(c+
": call ignored")}}return{getCode:(0,_.ca)("noop"),isParentVerifiable:(0,_.ca)(_.r),init:a("init"),setup:a("setup"),call:a("call")}}();_.Q&&(Ta=_.Q.na());var Go=_.u,Ho=_.u,ec=function(){if("flash"==Ta.rpctx)return _.Rb.Uf;if("rmr"==Ta.rpctx)return _.Rb.Km;var a="function"===typeof window.postMessage?_.Rb.Mj:"object"===typeof window.postMessage?_.Rb.Mj:window.ActiveXObject?_.Rb.Uf?_.Rb.Uf:_.Rb.bm?_.Rb.bm:_.Rb.pg:0<window.navigator.userAgent.indexOf("WebKit")?_.Rb.Km:"Gecko"===window.navigator.product?
_.Rb.frameElement:_.Rb.pg;a||(a=re);return a}();K[""]=function(){Io("Unknown RPC service: "+this.s)};K.__cb=function(a,c){var f=ja[a];f&&(delete ja[a],f.call(this,c))};return{Ba:function(c){"function"===typeof c.Mm&&(a=c.Mm)},R:function(a,c){("__cb"===a||"__ack"===a)&&(0,_.m)((0,window.Error)("i"));""===a&&(0,_.m)((0,window.Error)("j"));K[a]=c},Id:function(a){("__cb"===a||"__ack"===a)&&(0,_.m)((0,window.Error)("k"));""===a&&(0,_.m)((0,window.Error)("l"));delete K[a]},Am:function(a){K[""]=a},mn:function(){delete K[""]},
Gk:(0,_.x)(),call:function(a,c,f,g){a=a||"..";var h="..";".."===a?h=ok:"/"==a.charAt(0)&&(h=_.R.ka(window.location.href),h="/"+ok+(h?"|"+h:""));++Ca;f&&(ja[Ca]=f);var l={s:c,f:h,c:f?Ca:0,a:window.Array.prototype.slice.call(arguments,3),t:S[a],l:!!ka[a]},q;a:if("bidir"===wh||"c2p"===wh&&".."===a||"p2c"===wh&&".."!==a){q=window.location.href;var t="?";if("query"===nk)t="#";else if("hash"===nk)break a;t=q.lastIndexOf(t);t=-1===t?q.length:t;q=q.substring(0,t)}else q=_.s;q&&(l.r=q);".."!==a&&n(a)==_.s&&
!window.document.getElementById(a)||(q=Ya[a],!q&&n(a)!==_.s&&(q=ec),0===c.indexOf("legacy__")&&(q=ec,l.s=c.substring(8),l.c=l.c?l.c:Ca),l.g=_.r,l.r=h,q?(ka[a]&&(q=_.Rb.pg),q.call(a,h,l)===_.u&&(Ya[a]=re,ec.call(a,h,l))):If[a]?If[a].push(l):If[a]=[l])},Rk:v,Wg:w,Vg:A,tf:F,Ud:function(a){return S[a]},nj:function(a){delete U[a];delete ka[a];delete S[a];delete Za[a];delete Ya[a]},Qk:function(){return ec.Lk()},ym:function(a,c){4<a.length?ec.Vo(a,h):g.apply(_.s,a.concat(c))},zm:function(a){a.a=window.Array.prototype.slice.call(a.a);
window.setTimeout(function(){h(a)},0)},ka:l,Yd:function(a){var c=_.s,c=v(a);c||(c=(c=n(a))?c.origin:".."==a?Ta.parent:window.document.getElementById(a).src);return l(c)},ba:function(){ec.ba(h,c)===_.u&&(ec=re);Ww?F(".."):_.Qb.R("rpc",_.s,function(a){a=a.rpc||{};C(a);M(a)})},ek:q,Uo:n,b:"__ack",kh:ok||"..",j:0,i:1,d:2}}();_.R.ba()}else if("undefined"==typeof _.R||!_.R)_.R=window.gadgets.rpc,_.R.Ba=_.R.config,_.R.R=_.R.register,_.R.Id=_.R.unregister,_.R.Am=_.R.registerDefault,_.R.mn=_.R.unregisterDefault,
_.R.Gk=_.R.forceParentVerifiable,_.R.call=_.R.call,_.R.Rk=_.R.getRelayUrl,_.R.Wg=_.R.setRelayUrl,_.R.Vg=_.R.setAuthToken,_.R.tf=_.R.setupReceiver,_.R.Ud=_.R.getAuthToken,_.R.nj=_.R.removeReceiver,_.R.Qk=_.R.getRelayChannel,_.R.ym=_.R.receive,_.R.zm=_.R.receiveSameDomain,_.R.ka=_.R.getOrigin,_.R.Yd=_.R.getTargetOrigin,_.R.ek=_.R._getTargetWin,_.R.Uo=_.R._parseSiblingId;
(0,_.P)("gadgets.rpc.config",_.R.Ba);(0,_.P)("gadgets.rpc.register",_.R.R);(0,_.P)("gadgets.rpc.unregister",_.R.Id);(0,_.P)("gadgets.rpc.registerDefault",_.R.Am);(0,_.P)("gadgets.rpc.unregisterDefault",_.R.mn);(0,_.P)("gadgets.rpc.forceParentVerifiable",_.R.Gk);(0,_.P)("gadgets.rpc.call",_.R.call);(0,_.P)("gadgets.rpc.getRelayUrl",_.R.Rk);(0,_.P)("gadgets.rpc.setRelayUrl",_.R.Wg);(0,_.P)("gadgets.rpc.setAuthToken",_.R.Vg);(0,_.P)("gadgets.rpc.setupReceiver",_.R.tf);
(0,_.P)("gadgets.rpc.getAuthToken",_.R.Ud);(0,_.P)("gadgets.rpc.removeReceiver",_.R.nj);(0,_.P)("gadgets.rpc.getRelayChannel",_.R.Qk);(0,_.P)("gadgets.rpc.receive",_.R.ym);(0,_.P)("gadgets.rpc.receiveSameDomain",_.R.zm);(0,_.P)("gadgets.rpc.getOrigin",_.R.ka);(0,_.P)("gadgets.rpc.getTargetOrigin",_.R.Yd);

_.Nb=function(){function a(a){c(1,a)}function c(a,c){if(!(a<f)&&g)if(2===a&&g.warn)g.warn(c);else if(3===a&&g.error)try{g.error(c)}catch(n){}else g.log&&g.log(c)}_.Mb=function(a){c(2,a)};_.sa=function(a){c(3,a)};a.INFO=1;a.WARNING=2;a.NONE=4;var f=1,g=window.console?window.console:window.opera?window.opera.postError:_.p;return a}();

_.Q=_.Q||{};_.Q.De=function(a,c,f,g){"undefined"!=typeof a.addEventListener?a.addEventListener(c,f,g):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,f):(0,_.Mb)("cannot attachBrowserEvent: "+c)};_.Q.Wr=function(a,c,f,g){a.removeEventListener?a.removeEventListener(c,f,g):a.detachEvent?a.detachEvent("on"+c,f):(0,_.Mb)("cannot removeBrowserEvent: "+c)};

_.Ub=function(){function a(){h[0]=1732584193;h[1]=4023233417;h[2]=2562383102;h[3]=271733878;h[4]=3285377520;w=v=0}function c(a){for(var c=n,f=0;64>f;f+=4)c[f/4]=a[f]<<24|a[f+1]<<16|a[f+2]<<8|a[f+3];for(f=16;80>f;f++)c[f]=((c[f-3]^c[f-8]^c[f-14]^c[f-16])<<1|(c[f-3]^c[f-8]^c[f-14]^c[f-16])>>>31)&4294967295;a=h[0];for(var g=h[1],l=h[2],q=h[3],t=h[4],v,w,f=0;80>f;f++)40>f?20>f?(v=q^g&(l^q),w=1518500249):(v=g^l^q,w=1859775393):60>f?(v=g&l|q&(g|l),w=2400959708):(v=g^l^q,w=3395469782),v=((a<<5|a>>>27)&4294967295)+
v+t+w+c[f]&4294967295,t=q,q=l,l=(g<<30|g>>>2)&4294967295,g=a,a=v;h[0]=h[0]+a&4294967295;h[1]=h[1]+g&4294967295;h[2]=h[2]+l&4294967295;h[3]=h[3]+q&4294967295;h[4]=h[4]+t&4294967295}function f(a,f){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var g=[],h=0,n=a.length;h<n;++h)g.push(a.charCodeAt(h));a=g}f||(f=a.length);g=0;if(0==v)for(;g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64;for(;g<f;)if(l[v++]=a[g++],w++,64==v){v=0;for(c(l);g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64}}
function g(){var a=[],g=8*w;56>v?f(q,56-v):f(q,64-(v-56));for(var n=63;56<=n;n--)l[n]=g&255,g>>>=8;c(l);for(n=g=0;5>n;n++)for(var t=24;0<=t;t-=8)a[g++]=h[n]>>t&255;return a}for(var h=[],l=[],n=[],q=[128],t=1;64>t;++t)q[t]=0;var v,w;a();return{reset:a,update:f,yk:g,Of:function(){for(var a=g(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(window.Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c}}};

_.Vb=function(a){if("complete"===_.Ka.readyState)a();else{var c=_.u,f=function(){if(!c)return c=_.r,a.apply(this,arguments)};_.Ja.addEventListener?(_.Ja.addEventListener("load",f,_.u),_.Ja.addEventListener("DOMContentLoaded",f,_.u)):_.Ja.attachEvent&&(_.Ja.attachEvent("onreadystatechange",function(){"complete"===_.Ka.readyState&&f.apply(this,arguments)}),_.Ja.attachEvent("onload",f))}};
_.Wb=function(){function a(c){c=c||window.event;var f=c.screenX+c.clientX<<16,f=f+(c.screenY+c.clientY),f=f*((new window.Date).getTime()%1E6);n=n*f%q;0<g&&++h==g&&_.Q.Wr(window,"mousemove",a,_.u)}function c(a){var c=(0,_.Ub)();c.update(a);return c.Of()}var f=window.crypto;if(f&&"function"==typeof f.getRandomValues)return function(){var a=new window.Uint32Array(1);f.getRandomValues(a);return(0,window.Number)("0."+a[0])};var g=(0,_.O)("random/maxObserveMousemove");g==_.s&&(g=-1);var h=0,l=window.Math.random(),
n=1,q=1E6*(window.screen.width*window.screen.width+window.screen.height);0!=g&&_.Q.De(window,"mousemove",a,_.u);var t=c(window.document.cookie+"|"+window.document.location+"|"+(new window.Date).getTime()+"|"+l);return function(){var a=n,a=a+(0,window.parseInt)(t.substr(0,20),16);t=c(t);return a/(q+window.Math.pow(16,20))}}();
(0,_.P)("shindig.random",_.Wb);
_.Tb=window.iframer=window.iframer||{};_.T=window.iframes=window.iframes||{};
_.T.ip=function(a,c,f){var g=window.Array.prototype.slice.call(arguments);_.T.Pk(function(a){a.sameOrigin&&(g.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.R.call.apply(_.R,g))})};_.T.Tr=function(a,c){_.R.R(a,c)};

_.Xb=function(a){var c=(0,_.O)("googleapis.config/sessionIndex");c==_.s&&(c=window.__X_GOOG_AUTHUSER);if(c==_.s){var f=window.google;f&&(c=f.authuser)}c==_.s&&(a==_.s&&(a=window.location.href),c=a?(0,_.Va)(a,"authuser")||_.s:_.s);return c==_.s?_.s:(0,window.String)(c)};
_.Yb=function(a,c,f){a=(0,window.String)(a);if(((0,_.Va)(a,"authuser")||_.s)!=_.s||((0,_.Va)(a,"hd")||_.s)!=_.s)return a;c=(0,_.Xb)(c);if(f){var g=a,h=g.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(h&&h[0]){var l=h[1],n=h[4],q=h[5];h[3]=="/"+f&&(g=(l||"")+(n||"/")+(q||""))}if((h=g.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&h[0])return l=h[2],a=h[4]||h[5],q=h[6],c!=_.s&&(g=(l||"")+"/"+f+"/"+(0,window.encodeURIComponent)(c)+(a||"/")+
(q||"")),g}f=c==_.s?(0,window.encodeURIComponent)("authuser")+"=0":c.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)((0,window.String)(c)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(c)].join(""):["authuser=",(0,window.encodeURIComponent)(c)].join("");a=a.split("#");c=a[0].indexOf("?");0>c?a[0]=[a[0],"?",f].join(""):(g=[a[0]],c<a[0].length-1&&g.push("&"),g.push(f),a[0]=g.join(""));return g=a.join("#")};
_.Zb=_.Yb;
_.$b=function(a){_.T.Qg[a]||(_.T.Qg[a]={},_.R.R(a,function(c,f){var g=this.f;if("string"==typeof c&&!(c in{})&&!(g in{})){var h=this.callback,l=_.T.Qg[a][g],n;l&&window.Object.hasOwnProperty.call(l,c)?n=l[c]:window.Object.hasOwnProperty.call(_.T.Zd,a)&&(n=_.T.Zd[a]);if(n)return g=window.Array.prototype.slice.call(arguments,1),n._iframe_wrapped_rpc_&&h&&g.push(h),n.apply({},g)}(0,_.sa)(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',c,'" from frame "',g,'".'].join(""));
return _.s}));return _.T.Qg[a]};_.ac=function(a,c,f){function g(g){var l=window.Array.prototype.slice.call(arguments,0),n=l[l.length-1];if("function"===typeof n){var q=n;l.pop()}l.unshift(c,a,q,f);_.R.call.apply(_.R,l)}g._iframe_wrapped_rpc_=_.r;return g};_.bc=function(){window.setTimeout(function(){_.R.call("..","_noop_echo",_.T.Mr)},0)};_.cc=function(){_.R.R("_noop_echo",function(){this.callback(_.T.aq(_.T.Tc[this.f]))})};_.dc=function(a,c){var f=(0,_.ta)(_.xa,"watt",(0,_.N)());(0,_.ta)(f,a,c)};
_.fc=function(){return _.Ja.location.origin||_.Ja.location.protocol+"//"+_.Ja.location.host};_.gc=function(a){var c=(0,_.Va)(a.location.href,"urlindex");if(c=(0,_.ta)(_.xa,"fUrl",[])[c]){var f=a.location.hash,c=c+(/#/.test(c)?f.replace(/^#/,"&"):f);a.location.replace(c)}};_.hc=function(){_.T.Kl++;return["I",_.T.Kl,"_",(new window.Date).getTime()].join("")};
_.ic=function(a){if(0==a.indexOf("http:")||0==a.indexOf("https:")||0==a.indexOf("javascript:"))return a;if(0==a.indexOf("//"))return window.location.protocol+a;if(0==a.indexOf("/"))return window.location.protocol+"//"+window.location.host+a;var c=window.location.protocol+"//"+window.location.host+window.location.pathname;return c.substring(0,c.lastIndexOf("/")+1)+a};_.jc=function(a){return a instanceof window.Array?a.join(","):a instanceof window.Object?_.Lb.stringify(a):a};
_.kc=function(a,c,f){var g={},h=a.indexOf("#");-1==h?(g.hash=_.s,g.yc=a):(g.hash=a.substring(h+1),g.yc=a.substring(0,h));a=g.yc.indexOf("?");-1==a?g.mb=_.s:(g.mb=g.yc.substring(a+1),g.yc=g.yc.substring(0,a));a=f?g.hash?[g.hash]:[]:g.mb?[g.mb]:[];for(var l in c)c.hasOwnProperty(l)&&(h=(0,_.jc)(c[l]),a.push([(0,_.lc)(l),(0,_.lc)(h)].join("=")));f?g.hash=a.join("&"):g.mb=a.join("&");return g.yc+(g.mb?"?"+g.mb:"")+(g.hash?"#"+g.hash:"")};_.mc=function(){};
_.nc=function(){var a=(0,_.Xb)(_.p);return a!==_.p&&a!==_.s&&""!==a?"u/"+a+"/":""};_.oc=function(a){a=a||"";a=a.replace(/:session_prefix:/g,(0,_.nc)());a=a.replace(/:session_index:/g,(0,_.Xb)(_.p)||"0");return a=a.replace(/:socialhost:/g,(0,_.O)("iframes/:socialhost:"))};_.pc=function(a){a&&a.match(_.qc)&&(0,_.Ga)("googleapis.config/gcv",a)};_.rc=function(a){_.Sb.wh.ys(a)};_.sc=function(a){_.Sb.wh.qj(a)};_.tc=function(a,c){var f=c||{},g;for(g in a)a.hasOwnProperty(g)&&(f[g]=a[g]);return f};
_.uc=function(a,c,f,g,h){var l=[],n;for(n in a)if(a.hasOwnProperty(n)){var q=c,t=f,v=a[n],w=g,A=(0,_.$b)(n);A[q]=A[q]||{};w=_.Q.Dg(w,v);v._iframe_wrapped_rpc_&&(w._iframe_wrapped_rpc_=_.r);A[q][t]=w;l.push(n)}if(h)for(n in _.T.Zd)_.T.Zd.hasOwnProperty(n)&&l.push(n);return l.join(",")};_.vc=function(a,c,f){var g={};if(a&&a._methods){a=a._methods.split(",");for(var h=0;h<a.length;h++){var l=a[h];g[l]=(0,_.ac)(l,c,f)}}return g};
_.wc=function(a){return a&&a.disableMultiLevelParentRelay?_.u:_.Tb&&_.Tb._open&&"inline"!=a.style&&a.inline!==_.r&&!(a.container&&("string"==typeof a.container&&window.document.getElementById(a.container)||window.document==(a.container.ownerDocument||a.container.document)))};
_.xc=function(a,c){var f={},g=c.params||{},h;for(h in a)"#"==h.charAt(0)&&(f[h.substring(1)]=a[h]),0==h.indexOf("fr-")&&(f[h.substring(3)]=a[h]),"#"==g[h]&&(f[h]=a[h]);for(var l in f)delete a["fr-"+l],delete a["#"+l],delete a[l];return f};_.yc=function(a){if(":"==a.charAt(0)){var c=(0,_.O)("iframes/"+a.substring(1));a={};(0,_.Sa)(c,a);(c=a.url)&&(a.url=(0,_.ic)((0,_.oc)(c)));a.params||(a.params={});return a}return{url:(0,_.ic)((0,_.oc)(a))}};
_.zc=function(a,c){function f(){}f.prototype=c.prototype;a.prototype=new f};
_.Ac=function(a,c,f,g,h,l,n,q){this.Ba=(0,_.yc)(a);this.openParams=this.va=c;this.Ya=f||{};this.Na=g;this.$g=_.u;(0,_.Bc)(this,c.style);this.He={};(0,_.Cc)(this,function(){var a;(a=this.va.style)&&_.T.yf[a]?a=_.T.yf[a]:a?((0,_.Mb)(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=_.s):a=_.Dc;if(a){var c;if("function"===typeof a)c=a(this);else{var f={};for(c in a){var g=a[c];f[c]="function"===typeof g?_.Q.Dg(a,g,this):g}c=f}for(var n in h)a=c[n],"function"===typeof a&&
(0,_.Ec)(this,h[n],_.Q.Dg(c,a))}l&&(0,_.Ec)(this,"close",l)});this.wa=this.ac=n;this.ej=(q||[]).slice();n&&this.ej.unshift(n.ga())};_.Bc=function(a,c){if(!a.$g){var f=c&&!_.T.yf[c]&&_.T.Hh[c];f?(a.Gh=[],f(function(){a.$g=_.r;for(var c=0,f=a.Gh.length;c<f;++c)a.Gh[c].call(a)})):a.$g=_.r}};_.Cc=function(a,c){a.$g?c.call(a):a.Gh.push(c)};_.Ec=function(a,c,f){a.He[c]=a.He[c]||[];a.He[c].push(f)};_.Fc=function(a,c){return"number"==typeof c?{value:c,nd:c+"px"}:"100%"==c?{value:100,nd:"100%",Ul:_.r}:_.s};
_.Gc=function(a){return(0,_.kc)(a.Ba.url,a.Ya,_.u)};_.Hc=function(a,c,f,g,h,l,n){_.Ac.call(this,a,c,f,g,_.Ic,h,l,n);this.id=c.id||(0,_.hc)();this.d=c.rpcToken||window.Math.round(1E9*(0,_.Wb)());this.i=(0,_.xc)(this.Ya,this.Ba);this.Ph={};(0,_.Cc)(this,function(){this.Qb("open");(0,_.tc)(this.Ph,this)})};
_.Jc=function(a,c,f,g,h,l,n){_.Ac.call(this,a,c,f,g,_.Kc,h,l,n);this.url=a;this.b=_.s;this.jj=(0,_.hc)();(0,_.Cc)(this,function(){this.Qb("beforeparentopen");var a=(0,_.tc)(this.Na);a._onopen=this.Hr;a._ready=this.Jg;a._onclose=this.Gr;this.Ya._methods=(0,_.uc)(a,"..",this.jj,this,_.r);var a={},c;for(c in this.Ya)a[c]=(0,_.jc)(this.Ya[c]);var f=this.Ba.url;if(this.va.hideUrlFromParent){c=window.name;var g=f,f=(0,_.Gc)(this),h=a,a={};a._methods=h._methods;a["#opener"]=h["#opener"];a["#urlindex"]=h["#urlindex"];
a["#opener"]&&h["#urlindex"]!=_.p?(a["#opener"]=c+","+a["#opener"],c={url:g,Ya:a}):(g=(0,_.ta)(_.xa,"fUrl",[]),h=g.length,g[h]=f,_.xa.rUrl=_.gc,a["#opener"]=c,a["#urlindex"]=h,c=_.Sb.ka(_.Ja.location.href),f=(0,_.O)("iframes/relay_url_"+(0,window.encodeURIComponent)(c))||"/_/gapi/sibling/1/frame.html",c={url:c+f,Ya:a});f=c.url;a=c.Ya}_.Tb._open({url:f,openParams:this.va,params:a,proxyId:this.jj,openedByProxyChain:this.ej})})};
_.Lc=function(a,c,f,g,h,l,n){_.Ac.call(this,a,c,f,g,_.Kc,l,n);this.id=c.id||(0,_.hc)();this.d=h;g._close=this.close;this.onClosed=this.b;this.vn=0;(0,_.Cc)(this,function(){this.Qb("beforeparentopen");var a=(0,_.tc)(this.Na);this.Ya._methods=(0,_.uc)(a,"..",this.jj,this,_.r);var a=(0,_.kc)(this.Ba.url,this.Ya,_.u),a=_.Mc.Pt(_.Ka,a,this.id,{}),c=h.pm(a);this.canAutoClose=function(a){a(h.pk(c))};h.Tm(c,this);this.vn=c})};_.Nc=function(a){return _.T.yf[a]};_.Oc=function(a,c){_.T.yf[a]=c}; _.Pc=function(a){a=a||{};"auto"===a.height&&(a.height=_.Pb.ai());var c=window&&_.Qc&&_.Qc.la();c?c.Gm(a.width||0,a.height||0):_.Tb&&_.Tb._resizeMe&&_.Tb._resizeMe(a)};_.Rc=function(a){(0,_.pc)(a)};_.Mc={};
_.T.J=_.T.J||{};_.T.J.jp=function(a){try{return!!a.document}catch(c){}return _.u};_.T.J.Uk=function(a){var c=a.parent;return a!=c&&_.T.J.jp(c)?_.T.J.Uk(c):a};_.T.J.St=function(a){var c=a.userAgent||"";a=a.product||"";return 0!=c.indexOf("Opera")&&-1==c.indexOf("WebKit")&&"Gecko"==a&&0<c.indexOf("rv:1.")};
if(window.ToolbarApi)_.Qc=window.ToolbarApi,_.Qc.la=window.ToolbarApi.getInstance,_.Qc.prototype=window.ToolbarApi.prototype,_.B=_.Qc.prototype,_.B.pm=_.Qc.prototype.openWindow,_.B.sk=_.Qc.prototype.closeWindow,_.B.Tm=_.Qc.prototype.setOnCloseHandler,_.B.pk=_.Qc.prototype.canClosePopup,_.B.Gm=_.Qc.prototype.resizeWindow;else{_.Sc=_.s;_.Qc=(0,_.x)();_.Qc.la=function(){!_.Sc&&(window.external&&window.external.GTB_IsToolbar)&&(_.Sc=new _.Qc);return _.Sc};_.B=_.Qc.prototype;_.B.pm=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.B.sk=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.B.Tm=function(a,c){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,c)};_.B.pk=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.B.Gm=function(a,c){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,c)};window.ToolbarApi=_.Qc;window.ToolbarApi.getInstance=_.Qc.la};
_.qc=/^[-_.0-9A-Za-z]+$/;_.Ic={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"};_.Kc={onBeforeParentOpen:"beforeparentopen"};_.Dc={onOpen:function(a){var c=a.va;a.Oa(c.container||c.element);return a},onClose:function(a){a.remove()}};_.lc=window.encodeURIComponent||window.escape;_.T.Wp=function(a){var c=(0,_.N)();(0,_.Sa)(_.wb,c);(0,_.Sa)(a,c);return c};_.B=_.Ac.prototype;_.B.ci=(0,_.y)("va");
_.B.tb=(0,_.y)("Ya");_.B.bi=(0,_.y)("Na");_.B.ei=(0,_.y)("wa");_.B.da=function(a,c){(0,_.Cc)(this,function(){(0,_.Ec)(this,a,c)})};_.B.Vb=function(a,c){(0,_.Cc)(this,function(){var f=this.He[a];if(f)for(var g=0,h=f.length;g<h;++g)if(f[g]===c){f.splice(g,1);break}})};
_.B.Qb=function(a,c){var f,g=this.He[a];if(g)for(var h=window.Array.prototype.slice.call(arguments,1),l=0,n=g.length;l<n;++l)try{f=g[l].apply({},h)}catch(q){(0,_.sa)(['Exception when calling callback "',a,'" with exception "',q.name,": ",q.message,'".'].join(""))}return f};(0,_.zc)(_.Hc,_.Ac);_.B=_.Hc.prototype;
_.B.Oa=function(a,c){if(!this.Ba.url)return(0,_.sa)("Cannot open iframe, empty URL."),this;var f=this.id;_.T.Tc[f]=this;var g=(0,_.tc)(this.Na);g._ready=this.Jg;g._close=this.close;g._open=this.rm;g._resizeMe=this.Hm;g._renderstart=this.mm;var h=this.i;this.d&&(h.rpctoken=this.d);h._methods=(0,_.uc)(g,f,"",this,_.r);g=(0,_.Gc)(this);(0,_.kc)(g,h,_.r);this.U=a="string"===typeof a?window.document.getElementById(a):a;g=(0,_.Gc)(this);g=(0,_.kc)(g,h,_.r);h={id:f};if(c){h.attributes=c;var l=c.style;if("string"===
typeof l){var n;if(l){n=[];for(var l=l.split(";"),q=0,t=l.length;q<t;++q){var v=l[q];0==v.length&&q+1==t||(v=v.split(":"),2==v.length&&v[0].match(/^[ a-zA-Z_-]+$/)&&v[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?n.push(v.join(":")):(0,_.sa)(['Iframe style "',l[q],'" not allowed.'].join("")))}n=n.join(";")}else n="";c.style=n}}this.va.allowPost&&(h.allowPost=_.r);this.b=(0,_.ub)(g,a,h);_.T.Tc[f]=this;f=g;_.R.Vg(this.id,this.d);_.R.Wg(this.id,f);return this};_.B.ya=function(a,c){this.Ph[a]=c};_.B.ga=(0,_.y)("id");
_.B.Z=(0,_.y)("b");_.B.iq=(0,_.y)("U");_.B.Nc=(0,_.ba)("U");_.B.Jg=function(a){var c=(0,_.vc)(a,this.id,"");this.wa&&"function"==typeof this.Na._ready&&(a._methods=(0,_.uc)(c,this.wa.ga(),this.id,this,_.u),this.Na._ready(a));(0,_.tc)(a,this);(0,_.tc)(c,this);this.Qb("ready",a)};_.B.mm=function(a){this.Qb("renderstart",a)};_.B.close=function(a){a=this.Qb("close",a);delete _.T.Tc[this.id];return a};_.B.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.B.rm=function(a){var c=(0,_.vc)(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.U);if((0,_.wc)(a.openParams))new _.Jc(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain);else{var f=new _.Hc(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain),g=this;(0,_.Cc)(f,function(){var a={childId:f.ga()},l=f.Ph;l._toclose=f.close;a._methods=(0,_.uc)(l,g.id,f.id,f,_.u);c._onopen(a)})}};
_.B.Hm=function(a){if(this.Qb("resize",a)===_.p&&this.b){var c=(0,_.Fc)(this,a.width);c!=_.s&&(this.b.style.width=c.nd);a=(0,_.Fc)(this,a.height);a!=_.s&&(this.b.style.height=a.nd);if(this.b.parentElement&&(c!=_.s&&c.Ul||a!=_.s&&a.Ul))this.b.parentElement.style.display="block"}};(0,_.zc)(_.Jc,_.Ac);_.Jc.prototype.d=(0,_.y)("b");
_.Jc.prototype.Hr=function(a){this.b=a.childId;var c=(0,_.vc)(a,"..",this.b);(0,_.tc)(c,this);this.close=c._toclose;_.T.Tc[this.b]=this;this.wa&&this.Na._onopen&&(a._methods=(0,_.uc)(c,this.wa.ga(),this.b,this,_.u),this.Na._onopen(a))};_.Jc.prototype.Jg=function(a){var c=(0,window.String)(this.b),f=(0,_.vc)(a,"..",c);(0,_.tc)(a,this);(0,_.tc)(f,this);this.Qb("ready",a);this.wa&&this.Na._ready&&(a._methods=(0,_.uc)(f,this.wa.ga(),c,this,_.u),this.Na._ready(a))};
_.Jc.prototype.Gr=function(a){if(this.wa&&this.Na._onclose)this.Na._onclose(a);else return a=this.Qb("close",a),delete _.T.Tc[this.b],a};(0,_.zc)(_.Lc,_.Ac);_.Lc.prototype.close=function(a){a=this.Qb("close",a);this.d.sk(this.vn);return a};_.Lc.prototype.b=function(){this.Qb("close")};
(function(){_.T.Tc={};_.T.yf={};_.T.Hh={};_.T.Kl=0;_.T.Qg={};_.T.Zd={};_.T.Mg=_.s;_.T.Lg=[];_.T.Mr=function(a){var c=_.u;try{if(a!=_.s)var h=window.parent.frames[a.id],c=h.iframer.id==a.id&&h.iframes.openedId_(_.Tb.id)}catch(l){}try{_.T.Mg={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:c};for(a=0;a<_.T.Lg.length;++a)_.T.Lg[a](_.T.Mg);_.T.Lg=[]}catch(n){}};_.T.aq=function(a){var c=a&&a.wa,h=_.s;c&&(h={},h.id=c.ga(),h.proxyChain=
a.ej);return h};(0,_.cc)();if(window.parent!=window){var a=_.Q.na();a.gcv&&(0,_.pc)(a.gcv);var c=a.jsh;c&&(0,_.rc)(c);(0,_.tc)((0,_.vc)(a,"..",""),_.Tb);(0,_.tc)(a,_.Tb);(0,_.bc)()}_.T.qa=_.Nc;_.T.ma=_.Oc;_.T.xs=_.Rc;_.T.Zc=_.Pc;_.T.Rp=function(a){return _.T.Hh[a]};_.T.rj=function(a,c){_.T.Hh[a]=c};_.T.cs=_.Pc;_.T.Ds=_.Rc;_.T.ng={};_.T.ng.get=_.Nc;_.T.ng.set=_.Oc;_.T.Zo=function(a,c){(0,_.$b)(a);_.T.Zd[a]=c||window[a]};_.T.Mt=function(a){delete _.T.Zd[a]};_.T.open=function(a,c,h,l,n,q){3==arguments.length?
l={}:4==arguments.length&&"function"===typeof l&&(n=l,l={});var t="bubble"===c.style&&_.Qc&&_.Qc.la();return t?new _.Lc(a,c,h,l,t,n,q):(0,_.wc)(c)?new _.Jc(a,c,h,l,n,q):new _.Hc(a,c,h,l,n,q)};_.T.close=function(a,c){_.Tb&&_.Tb._close&&_.Tb._close(a,c)};_.T.Ub=function(a,c,h){2==arguments.length&&"function"===typeof n&&(h=c,c={});var l=a||{};"height"in l||(l.height=_.Pb.ai());var n=c||{};l._methods=(0,_.uc)(n,"..","",_.Tb,_.r);_.Tb&&_.Tb._ready&&_.Tb._ready(l,h)};_.T.Pk=function(a){_.T.Mg?a(_.T.Mg):
_.T.Lg.push(a)};_.T.Jr=function(a){return!!_.T.Tc[a]};_.T.Vp=function(){return["https://ssl.gstatic.com/gb/js/",(0,_.O)("googleapis.config/gcv")].join("")};_.T.Rr=function(a){var c={mouseover:1,mouseout:1};if(_.Tb._event)for(var h=0;h<a.length;h++){var l=a[h];l in c&&_.Q.De(window.document,l,function(a){_.Tb._event({event:a.type,timestamp:(new window.Date).getTime()})},_.r)}};_.T.zs=_.rc;_.T.qj=_.sc;_.T.lr=_.mc;_.T.ar=_.Tb})();
(0,_.P)("iframes.allow",_.T.Zo);(0,_.P)("iframes.callSiblingOpener",_.T.ip);(0,_.P)("iframes.registerForOpenedSibling",_.T.Tr);(0,_.P)("iframes.close",_.T.close);(0,_.P)("iframes.getGoogleConnectJsUri",_.T.Vp);(0,_.P)("iframes.getHandler",_.T.qa);(0,_.P)("iframes.getDeferredHandler",_.T.Rp);(0,_.P)("iframes.getParentInfo",_.T.Pk);(0,_.P)("iframes.iframer",_.T.ar);(0,_.P)("iframes.open",_.T.open);(0,_.P)("iframes.openedId_",_.T.Jr);(0,_.P)("iframes.propagate",_.T.Rr);(0,_.P)("iframes.ready",_.T.Ub);
(0,_.P)("iframes.resize",_.T.Zc);(0,_.P)("iframes.setGoogleConnectJsVersion",_.T.xs);(0,_.P)("iframes.setBootstrapHint",_.T.qj);(0,_.P)("iframes.setJsHint",_.T.zs);(0,_.P)("iframes.setHandler",_.T.ma);(0,_.P)("iframes.setDeferredHandler",_.T.rj);(0,_.P)("IframeBase",_.Ac);(0,_.P)("IframeBase.prototype.addCallback",_.Ac.prototype.da);(0,_.P)("IframeBase.prototype.getMethods",_.Ac.prototype.bi);(0,_.P)("IframeBase.prototype.getOpenerIframe",_.Ac.prototype.ei);
(0,_.P)("IframeBase.prototype.getOpenParams",_.Ac.prototype.ci);(0,_.P)("IframeBase.prototype.getParams",_.Ac.prototype.tb);(0,_.P)("IframeBase.prototype.removeCallback",_.Ac.prototype.Vb);(0,_.P)("Iframe",_.Hc);(0,_.P)("Iframe.prototype.close",_.Hc.prototype.close);(0,_.P)("Iframe.prototype.exposeMethod",_.Hc.prototype.ya);(0,_.P)("Iframe.prototype.getId",_.Hc.prototype.ga);(0,_.P)("Iframe.prototype.getIframeEl",_.Hc.prototype.Z);(0,_.P)("Iframe.prototype.getSiteEl",_.Hc.prototype.iq);
(0,_.P)("Iframe.prototype.openInto",_.Hc.prototype.Oa);(0,_.P)("Iframe.prototype.remove",_.Hc.prototype.remove);(0,_.P)("Iframe.prototype.setSiteEl",_.Hc.prototype.Nc);(0,_.P)("Iframe.prototype.addCallback",_.Hc.prototype.da);(0,_.P)("Iframe.prototype.getMethods",_.Hc.prototype.bi);(0,_.P)("Iframe.prototype.getOpenerIframe",_.Hc.prototype.ei);(0,_.P)("Iframe.prototype.getOpenParams",_.Hc.prototype.ci);(0,_.P)("Iframe.prototype.getParams",_.Hc.prototype.tb);
(0,_.P)("Iframe.prototype.removeCallback",_.Hc.prototype.Vb);(0,_.P)("IframeProxy",_.Jc);(0,_.P)("IframeProxy.prototype.getTargetIframeId",_.Jc.prototype.d);(0,_.P)("IframeProxy.prototype.addCallback",_.Jc.prototype.da);(0,_.P)("IframeProxy.prototype.getMethods",_.Jc.prototype.bi);(0,_.P)("IframeProxy.prototype.getOpenerIframe",_.Jc.prototype.ei);(0,_.P)("IframeProxy.prototype.getOpenParams",_.Jc.prototype.ci);(0,_.P)("IframeProxy.prototype.getParams",_.Jc.prototype.tb);
(0,_.P)("IframeProxy.prototype.removeCallback",_.Jc.prototype.Vb);(0,_.P)("IframeWindow",_.Lc);(0,_.P)("IframeWindow.prototype.close",_.Lc.prototype.close);(0,_.P)("IframeWindow.prototype.onClosed",_.Lc.prototype.b);(0,_.P)("iframes.util.getTopMostAccessibleWindow",_.T.J.Uk);(0,_.P)("iframes.handlers.get",_.T.ng.get);(0,_.P)("iframes.handlers.set",_.T.ng.set);(0,_.P)("iframes.resizeMe",_.T.cs);(0,_.P)("iframes.setVersionOverride",_.T.Ds);

_.Tc=function(a){var c=(0,_.ya)();return c?c(a):_.u};_.Uc=(0,_.ta)(_.xa,"rw",(0,_.N)());
_.Vc=function(a,c){var f=_.Uc[a];f&&f.state<c&&(f.state=c)};_.Wc=function(a){a=(a=_.Uc[a])?a.oid:_.p;if(a){var c=_.Ka.getElementById(a);c&&c.parentNode.removeChild(c);delete _.Uc[a];(0,_.Wc)(a)}};_.Xc=function(a){a=a.style;a.textIndent="0";a.margin="0";a.padding="0";a.background="transparent";a.borderStyle="none";a.cssFloat="none";a.styleFloat="none";a.lineHeight="normal";a.fontSize="1px";a.verticalAlign="baseline"};
(function(){function a(a){a=a.va.container;"string"===typeof a&&(a=window.document.getElementById(a));return a}function c(a){var c=a.clientWidth;return"position:absolute;top:-10000px;width:"+(c?c+"px":a.style.width||"300px")+";margin:0px;border-style:none;"}function f(a,c){var f={};f.width=c?c.width:a.width;f.height=c?c.height:a.height;var g=a.Z(),t=a.ga();(0,_.Vc)(t,2);(t=_.Uc[t])&&(t.args=f);a:{t=g.parentNode;f=f||{};if((0,_.Tc)()){if("number"===typeof _.xa.ucs)break a;var v=g.id;if(v){var w;w=
(w=_.Uc[v])?w.state:_.p;if(1===w||4===w)break a;(0,_.Wc)(v)}}w=f.width;f=f.height;(0,_.Xc)(t);t.style.display="inline-block";g=g.style;g.position="static";g.left=0;g.top=0;g.visibility="visible";w&&(g.width=w+"px");f&&(g.height=f+"px");v&&(0,_.Vc)(v,3)}(v=c?c.title:_.s)&&a.Z().setAttribute("title",v)}var g={open:function(f){var g=a(f);return f.Oa(g,{style:c(g,f)})},attach:function(f,g){var n=a(f),q=g.id,t=g.getAttribute("data-postorigin")||g.src,v=/#(?:.*&)?rpctoken=(\d+)/.exec(t),v=v&&v[1];f.id=
q;f.d=v;f.U=g.parentNode;f.b=g;_.T.Tc[q]=f;v=(0,_.tc)(f.Na);v._ready=f.Jg;v._close=f.close;v._open=f.rm;v._resizeMe=f.Hm;v._renderstart=f.mm;(0,_.uc)(v,q,"",f,_.r);_.R.Vg(f.id,f.d);_.R.Wg(f.id,t);var n=_.T.Wp({style:c(n,f)}),w;for(w in n)window.Object.prototype.hasOwnProperty.call(n,w)&&("style"==w?f.b.style.cssText=n[w]:f.b.setAttribute(w,n[w]))}};g.onready=f;g.onRenderStart=f;g.close=function(a){var c=a.U;c&&c.removeChild(a.Z())};_.T.ma("inline",g)})();


_.Yc=function(a){var c;a.match(/^https?%3A/i)&&(c=(0,window.decodeURIComponent)(a));a=c?c:a;return(0,_.va)(window.document,a)};_.Zc=function(a){a=a||"canonical";for(var c=window.document.getElementsByTagName("link"),f=0,g=c.length;f<g;f++){var h=c[f],l=h.getAttribute("rel");if(l&&l.toLowerCase()==a&&(h=h.getAttribute("href")))return(0,_.Yc)(h)}return window.location.href};_.$c=function(a,c,f,g){return(a="string"==typeof a?a:_.p)?(0,_.Yc)(a):(0,_.Zc)(g)};
_.ad=function(a){return"string"==typeof a?""!=a&&"0"!=a&&"false"!=a.toLowerCase():!!a};_.bd=function(a){var c=(0,window.parseInt)(a,10);if(c==a)return(0,window.String)(c)};_.cd=function(a){if((0,_.ad)(a))return"true"};_.dd=function(a){return"string"==typeof a&&_.ed[a.toLowerCase()]?a.toLowerCase():"standard"};_.fd=function(a,c){return"tall"==(0,_.dd)(c)?"true":a==_.s||(0,_.ad)(a)?"true":"false"};_.gd=function(a,c,f){a==_.s&&f&&(a=f.db,a==_.s&&(a=f.gwidget&&f.gwidget.db));return a||_.p};
_.hd=function(a,c,f){a==_.s&&f&&(a=f.ecp,a==_.s&&(a=f.gwidget&&f.gwidget.ecp));return a||_.p};_.ed={tall:{"true":{width:50,height:60},"false":{width:50,height:24}},small:{"false":{width:24,height:15},"true":{width:70,height:15}},medium:{"false":{width:32,height:20},"true":{width:90,height:20}},standard:{"false":{width:38,height:24},"true":{width:106,height:24}}};
_.id={href:[_.$c,"url"],width:[_.bd],size:[_.dd],resize:[_.cd],autosize:[_.cd],count:[function(a,c){return(0,_.fd)(c.count,c.size)}],db:[_.gd],ecp:[_.hd],textcolor:[function(a){if("string"==typeof a&&a.match(/^[0-9A-F]{6}$/i))return a}],drm:[_.cd],recommendations:[],fu:[],ad:[_.cd],cr:[_.bd],ag:[_.bd],"fr-ai":[],"fr-sigh":[]};


_.jd=(0,_.wa)();
_.kd=function(a,c){if(!_.ld){var f=(0,_.O)("iframes/:socialhost:"),g=(0,_.Xb)(_.p)||"0",h=(0,_.Xb)(_.p);_.ld={socialhost:f,session_index:g,session_prefix:h!==_.p&&h!==_.s&&""!==h?"u/"+h+"/":"",im_prefix:(0,_.O)("googleapis.config/signedIn")===_.u?"_/im/":""}}return _.ld[c]||""};_.md=function(a,c,f){return(0,_.$c)(a,c,f,c.action?_.p:"publisher")};_.nd=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};
_.od=function(a){var c=_.p;"number"===typeof a?c=a:"string"===typeof a&&(c=(0,window.parseInt)(a,10));return c};_.pd=function(a,c){if("string"==typeof a){a=a.toLowerCase();var f;for(f=0;f<c.length;f++)if(c[f]==a)return a}};_.qd=function(a){return(0,_.pd)(a,_.rd)};_.sd=function(a){return(0,_.pd)(a,_.td)};_.ud=function(a){a.source=[_.s,"source"];a.expandTo=[_.s,"expandTo"];a.align=[_.sd];a.annotation=[_.qd];a.origin=[_.nd]};_.vd=function(a){var c=(0,_.ta)(_.xa,"sws",[]);return 0<=_.Ob.call(c,a)};
_.wd=function(a,c){if("complete"!==_.Ka.readyState)try{a()}catch(f){}(0,_.Vb)(c)};_.xd=function(a){if(_.ua.test(window.Object.keys))return window.Object.keys(a);var c=[],f;for(f in a)(0,_.Ra)(a,f)&&c.push(f);return c};
_.yd=function(a,c){_.zd.ps0=(0,_.Ad)();(0,_.Bd)("ps0");var f=("string"===typeof a?window.document.getElementById(a):a)||_.Ka,g;g=_.Ka.documentMode;if(f.querySelectorAll&&(!g||8<g)){g=c?[c]:(0,_.xd)(_.Cd).concat((0,_.xd)(_.Dd)).concat((0,_.xd)(_.Ed));for(var h=[],l=0;l<g.length;l++){var n=g[l];h.push(".g-"+n,"g\\:"+n)}g=f.querySelectorAll(h.join(","))}else g=f.getElementsByTagName("*");f=(0,_.N)();for(h=0;h<g.length;h++){l=g[h];var q=l,n=c,t=q.nodeName.toLowerCase(),v=_.p;q.getAttribute("data-gapiscan")?
n=_.s:(0==t.indexOf("g:")?v=t.substr(2):(q=(q=(0,window.String)(q.className||q.getAttribute("class")))&&_.Fd.exec(q))&&(v=q[1]),n=v&&(_.Cd[v]||_.Dd[v]||_.Ed[v])&&(!n||v===n)?v:_.s);n&&(l.setAttribute("data-gapiscan",_.r),(0,_.ta)(f,n,[]).push(l))}for(var w in f)_.Gd.push(w);_.zd.ps1=(0,_.Ad)();(0,_.Bd)("ps1");(w=_.Gd.join(":"))&&_.La.load(w,_.p);var A,l=[];for(A in f){h=f[A];g=0;for(w=h.length;g<w;g++){for(var q=h[g],n=A,t=v=q,q=(0,_.N)(),C=0!=t.nodeName.toLowerCase().indexOf("g:"),M=0,I=t.attributes.length;M<
I;M++){var F=t.attributes[M],K=F.name,F=F.value;0<=_.Ob.call(_.Hd,K)||(C&&0!=K.indexOf("data-")||"null"===F)||(C&&(K=K.substr(5)),q[K.toLowerCase()]=F)}t=t.style;(C=(0,_.od)(t&&t.height))&&(q.height=(0,window.String)(C));(t=(0,_.od)(t&&t.width))&&(q.width=(0,window.String)(t));(0,_.Id)(n,v,q,l,w)}}};
_.Jd=function(a,c){var f=(0,_.ta)(_.xa,"watt",(0,_.N)())[a];c&&f?(f(c),(f=c.iframeNode)&&f.setAttribute("data-gapiattached",_.r)):_.La.load(a,function(){var f=(0,_.ta)(_.xa,"watt",(0,_.N)())[a],h=c&&c.iframeNode;!h||!f?(0,_.La[a].go)(h&&h.parentNode):(f(c),h.setAttribute("data-gapiattached",_.r))})};
_.Id=function(a,c,f,g,h){switch((0,_.Kd)(c,a)){case 0:a=_.Ed[a]?a+"_annotation":a;g={};g.iframeNode=c;g.userParams=f;(0,_.Jd)(a,g);break;case 1:if(c.parentNode){var l=_.r;f.dontclear&&(l=_.u);delete f.dontclear;var n,q,t;q=t=a;"plus"==a&&f.action&&(t=a+"_"+f.action,q=a+"/"+f.action);(t=(0,_.O)("iframes/"+t+"/url"))||(t=":socialhost:/_/widget/render/"+q);q=t.replace(_.Ld,_.kd);t={};(0,_.Sa)(f,t);t.hl=(0,_.O)("lang")||"en-US";t.origin=(0,_.nd)();t.exp=(0,_.O)("iframes/"+a+"/params/exp");var v=(0,_.O)("iframes/"+
a+"/params/location");if(v)for(var w=0;w<v.length;w++){var A=v[w];t[A]=_.Ja.location[A]}switch(a){case "plus":t.url=(0,_.md)(t.href,f,_.s);delete t.href;break;case "plusone":case "recobox":t.url=f.href?(0,_.Yc)(f.href):(0,_.Zc)();t.db=(0,_.gd)(f.db,_.p,(0,_.O)());t.ecp=(0,_.hd)(f.ecp,_.p,(0,_.O)());delete t.href;break;case "signin":t.url=(0,_.Zc)()}t.hl=(0,_.O)("lang")||"en-US";_.xa.ILI&&(t.iloader="1");delete t["data-onload"];delete t.rd;t.gsrc=(0,_.O)("iframes/:source:");v=(0,_.O)("inline/css");
"undefined"!==typeof v&&(0<h&&v>=h)&&(t.ic="1");v=/^#|^fr-/;h={};for(var C in t)(0,_.Ra)(t,C)&&v.test(C)&&(h[C.replace(v,"")]=t[C],delete t[C]);C=[].concat(_.Md);v=(0,_.O)("iframes/"+a+"/methods");"object"===typeof v&&_.ua.test(v.push)&&(C=C.concat(v));for(n in f)if((0,_.Ra)(f,n)&&/^on/.test(n)&&("plus"!=a||"onconnect"!=n))C.push(n),delete t[n];delete t.callback;h._methods=C.join(",");n=(0,_.eb)(q,t,h);f.rd?C=c:(C=window.document.createElement("div"),c.setAttribute("data-gapistub",_.r),C.style.cssText=
"position:absolute;width:100px;left:-10000px;",c.parentNode.insertBefore(C,c));C.id||(c=C,(0,_.ta)(_.jd,a,0),q="___"+a+"_"+_.jd[a]++,c.id=q);c=(0,_.N)();c[">type"]=a;(0,_.Sa)(f,c);C.setAttribute("data-gwattr",(0,_.ab)(c).join(":"));c=C;C={allowPost:1,attributes:_.Nd};C.dontclear=!l;c=(0,_.ub)(n,c,C);l={};l.userParams=f;l.url=n;l.type=a;l.iframeNode=c;l.id=c.getAttribute("id");f=l.id;c=(0,_.N)();c.id=f;c.userParams=l.userParams;c.url=l.url;c.type=l.type;c.state=1;_.Uc[f]=c;f=l}else f=_.s;f&&((l=f.id)&&
g.push(l),(0,_.Jd)(a,f))}};_.Kd=function(a,c){if(a&&1===a.nodeType&&c)if(_.Ed[c]){if(_.Od[a.nodeName.toLowerCase()]){var f=a.innerHTML;return f&&f.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")?0:1}}else{if(_.Dd[c])return 0;if(_.Cd[c])return 1}return _.s};_.Pd=function(a,c,f,g){_.Qd[f]=_.Qd[f]||!!g;(0,_.ta)(_.Rd,f,[]);_.Rd[f].push([a,c])};_.Bd=function(a,c,f){var g=_.Sd.r;"function"===typeof g?g(a,c,f):g.push([a,c,f])};_.Ad=function(){return(new window.Date).getTime()};
_.Td=function(a,c,f,g){"_p"==c&&(0,_.m)((0,window.Error)("n`_p"));(0,_.Ud)(c,f)[a]=g||(0,_.Ad)();(0,_.Bd)(a,c,f)};_.Ud=function(a,c){var f=(0,_.ta)(_.Vd,a,(0,_.N)());return(0,_.ta)(f,c,(0,_.N)())};_.Wd=function(a,c,f){var g=_.s;c&&f&&(g=(0,_.Ud)(c,f)[a]);return g||_.zd[a]};_.Xd=function(a,c){this.type=!a?"g":"_p"==a?"m":"w";this.name=a;this.b=c};
_.Yd=function(a){var c=[];c.push("l"+((0,_.O)("isPlusUser")?"1":"0"));var f="m"+(_.Zd?"1":"0");c.push(f);if("m"==a.type)c.push("p"+a.b);else if("w"==a.type){var g="n"+a.b;c.push(g);"0"==a.b&&c.push(f+g)}return c};_.$d=function(a,c,f){for(var g=new _.Xd(c,f),h=(0,_.ta)(_.ae,g.key(),(0,_.N)()),l=_.Rd[a]||[],n=0;n<l.length;++n){var q=l[n],t=h,v=q[0],w=a,A=c,C=f,q=(0,_.Wd)(q[1],A,C),w=(0,_.Wd)(w,A,C);t[v]=q&&w?w-q:_.s}_.Qd[a]&&_.be&&((0,_.ce)(_.de),(0,_.ce)(g))};
_.ee=function(a,c){c=c||[];for(var f=[],g=0;g<c.length;g++)f.push(a+c[g]);return f};
_.ce=function(a){var c=_.Ja.__gapi_jstiming__;c.sn=_.fe[a.type];var f=new c.Timer(0),g;a:{switch(a.type){case "g":g="global";break a;case "m":g=a.b;break a;case "w":g=a.name;break a}g=_.p}f.name=g;g=_.u;var h=a.key(),l=_.ae[h];f.tick("_start",_.s,0);for(var n in l)f.tick(n,"_start",l[n]),g=_.r;_.ae[h]=(0,_.N)();if(g){n=[];g=(0,_.O)("lexps");n=n.concat((0,_.ee)("e",g));n=n.concat((0,_.ee)("",(0,_.Yd)(a)));for(h=0;h<_.ge.length;h++)l=_.ge[h],0<=_.Ob.call(g,l)&&(n=n.concat((0,_.ee)(l?"e"+l:"",(0,_.Yd)(a))));
n=(0,_.ee)("abc_",n);c.report(f,{e:n.join(",")})}};_.he=function(){};_.ld=_.s;_.Ld=/:([a-zA-Z_]+):/g;_.Md="onPlusOne _ready _close,_open _resizeMe _renderstart oncircled".split(" ");_.rd="inline bubble none only pp vertical-bubble".split(" ");_.td=["left","right"];_.Hd=["style","data-gapiscan"];_.Nd={style:"position:absolute;top:-10000px;width:300px;margin:0px;borderStyle:none"};_.Od={button:_.r,div:_.r,span:_.r};_.Fd=/(?:^|\s)g-((\S)*)(?:$|\s)/;_.Cd=(0,_.ta)(_.xa,"SW",(0,_.N)()); _.Dd=(0,_.ta)(_.xa,"SA",(0,_.N)());_.Ed=(0,_.ta)(_.xa,"SM",(0,_.N)());_.Gd=(0,_.ta)(_.xa,"FW",[]);
(0,_.ta)(_.La,"platform",{}).go=_.yd;_.Sd=(0,_.ta)(_.xa,"perf",(0,_.N)());_.zd=(0,_.ta)(_.Sd,"g",(0,_.N)());_.Vd=(0,_.ta)(_.Sd,"i",(0,_.N)());(0,_.ta)(_.Sd,"r",[]);_.Qd=(0,_.N)();_.Rd=(0,_.N)();(function(){function a(a){this.t={};this.tick=function(a,c,f){this.t[a]=[f!=_.p?f:(new window.Date).getTime(),c]};this.tick("start",_.s,a)}var c=new a;window.__gapi_jstiming__={Timer:a,load:c};if(window.performance&&window.performance.timing){var c=window.performance.timing,f=window.__gapi_jstiming__.load,g=c.navigationStart,c=c.responseStart;0<g&&c>=g&&(f.tick("_wtsrt",_.p,g),f.tick("wtsrt_","_wtsrt",c),f.tick("tbsd_","wtsrt_"))}try{c=_.s,window.chrome&&window.chrome.csi&&(c=window.Math.floor(window.chrome.csi().pageT),
f&&0<g&&(f.tick("_tbnd",_.p,window.chrome.csi().startE),f.tick("tbnd_","_tbnd",g))),c==_.s&&window.gtbExternal&&(c=window.gtbExternal.pageT()),c==_.s&&window.external&&(c=window.external.pageT,f&&0<g&&(f.tick("_tbnd",_.p,window.external.startE),f.tick("tbnd_","_tbnd",g))),c&&(window.__gapi_jstiming__.pt=c)}catch(h){}})();
if(window.__gapi_jstiming__){window.__gapi_jstiming__.nk={};window.__gapi_jstiming__.Zr=1;_.ie=function(a,c,f){var g=a.t[c],h=a.t.start;if(g&&(h||f))return g=a.t[c][0],f!=_.p?h=f:h=h[0],g-h};window.__gapi_jstiming__.getTick=_.ie;window.__gapi_jstiming__.getLabels=function(a){var c=[],f;for(f in a.t)c.push(f);return c};_.je=function(a,c,f){var g="";window.__gapi_jstiming__.pt&&(g+="&srt="+window.__gapi_jstiming__.pt);try{window.external&&window.external.tran?g+="&tran="+window.external.tran:window.gtbExternal&&
window.gtbExternal.tran?g+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(g+="&tran="+window.chrome.csi().tran)}catch(h){}var l=window.chrome;if(l&&(l=l.loadTimes)){l().wasFetchedViaSpdy&&(g+="&p=s");if(l().wasNpnNegotiated){var g=g+"&npn=1",n=l().npnNegotiatedProtocol;n&&(g+="&npnv="+(window.encodeURIComponent||window.escape)(n))}l().wasAlternateProtocolAvailable&&(g+="&apa=1")}var q=a.t,t=q.start,l=[],n=[],v;for(v in q)if("start"!=v&&0!=v.indexOf("_")){var w=q[v][1];w?q[w]&&
n.push(v+"."+(0,_.ie)(a,v,q[w][0])):t&&l.push(v+"."+(0,_.ie)(a,v))}if(c)for(var A in c)g+="&"+A+"="+c[A];(c=f)||(c="https:"==window.document.location.protocol?"https://csi.gstatic.com/csi":"http://csi.gstatic.com/csi");return[c,"?v=3","&s="+(window.__gapi_jstiming__.sn||"gwidget")+"&action=",a.name,n.length?"&it="+n.join(","):"","",g,"&rt=",l.join(",")].join("")};_.ke=function(a,c,f){a=(0,_.je)(a,c,f);if(!a)return"";c=new window.Image;var g=window.__gapi_jstiming__.Zr++;window.__gapi_jstiming__.nk[g]=
c;c.onload=c.onerror=function(){window.__gapi_jstiming__&&delete window.__gapi_jstiming__.nk[g]};c.src=a;c=_.s;return a};window.__gapi_jstiming__.report=function(a,c,f){if("prerender"==window.document.webkitVisibilityState){var g=_.u,h=function(){if(!g){c?c.prerender="1":c={prerender:"1"};var l;"prerender"==window.document.webkitVisibilityState?l=_.u:((0,_.ke)(a,c,f),l=_.r);l&&(g=_.r,window.document.removeEventListener("webkitvisibilitychange",h,_.u))}};window.document.addEventListener("webkitvisibilitychange", h,_.u);return""}return(0,_.ke)(a,c,f)}};
_.ge=[73,74,77,78];_.fe={g:"gapi_global",m:"gapi_module",w:"gwidget"};_.Xd.prototype.key=function(){switch(this.type){case "g":return this.type;case "m":return this.type+"."+this.b;case "w":return this.type+"."+this.name+this.b}};_.de=new _.Xd;_.Zd=window.navigator.userAgent.match(/iPhone|iPad|Android|PalmWebOS|Maemo|Bada/);_.ae=(0,_.ta)(_.Sd,"_c",(0,_.N)());_.be=window.Math.random()<((0,_.O)("csi/rate")||0);(0,_.Pd)("blt","bs0","bs1");(0,_.Pd)("psi","ps0","ps1");(0,_.Pd)("rpcqi","rqe","rqd");
(0,_.Pd)("mli","ml0","ml1");(0,_.Pd)("mei","me0","me1",_.r);(0,_.Pd)("wci","wrs","wdc");(0,_.Pd)("wdi","wrs","wrdi");(0,_.Pd)("wdt","bs0","wrdt");(0,_.Pd)("wri","wrs","wrri",_.r);(0,_.Pd)("wrt","bs0","wrrt");(0,_.Pd)("wji","wje0","wje1",_.r);(0,_.Pd)("wjli","wjl0","wjl1");(0,_.Pd)("whi","wh0","wh1",_.r);_.le=_.Sd.r;if("function"!==typeof _.le){for(_.me;_.me=_.le.shift();)_.$d.apply(_.s,_.me);_.Sd.r=_.$d};
_.ne=function(){function a(a){return a}function c(a){var c=(0,_.O)(a);return"undefined"!==typeof c?c:(0,_.O)("gwidget/"+a)}function f(a){return function(c){var f=a;"number"===typeof c?f=c:"string"===typeof c&&(f=c.indexOf("px"),-1!=f&&(c=c.substring(0,f)),f=(0,window.parseInt)(c,10));return f}}function g(a){"string"===typeof a&&(a=window[a]);return"function"===typeof a?a:_.s}function h(){return c("lang")||"en-US"}function l(a){if(!_.T.qa("attach")){var c={},f=_.T.qa("inline"),g;for(g in f)f.hasOwnProperty(g)&&
(c[g]=f[g]);c.open=function(a){var c=window.document.getElementById(a.va.renderData.id);c||(0,_.m)((0,window.Error)("o"));return f.attach(a,c)};_.T.ma("attach",c)}a.style="attach"}function n(a){function c(a){for(var g={},h=0;h<a.length;++h)g[a[h].toLowerCase()]=1;g[f.Xs]=1;f.pr=g}var f={};f.Gb=a[0];f.Lj=-1;f.tn="___"+f.Gb+"_";f.Xs="g:"+f.Gb;f.Wt="g-"+f.Gb;f.Dm=[];f.Ba={};f.zh=[];f.Qh=[];a[1]&&(f.Kr=a[1]);(function(a){f.Ba=a;for(var c in Ca)Ca.hasOwnProperty(c)&&!f.Ba.hasOwnProperty(c)&&(f.Ba[c]=Ca[c])})(a[2]||
{});a[3]&&(f.zh=a[3]);a[4]&&c(a[4]);a[5]&&(f.ne=a[5]);f.nu=a[7]===_.r;f.Pr=a[8];f.pr||c(F);if(a=a[6])if("number"==typeof a.length){f.Qh=a;for(var h=a.length-1;0<=h;--h)f.Ba[a[h]]=[g]}else for(h in a)a.hasOwnProperty(h)&&!f.Ba.hasOwnProperty(h)&&(f.Qh.push(h),f.Ba[h]=a[h]);f.cj=function(a){f.Lj++;(0,_.Td)("wrs",f.Gb,(0,window.String)(f.Lj));var c=[];f.ne&&(c[0]=a.element,c[1]=a.Rg,f.ne("s",c),a.Rg=c[1]);var g=a.element,h=g.parentNode,n=a.Ba;if(0===a.Rg){var A=window.document.createElement("div");h.insertBefore(A,
g);h.removeChild(g);g=A}A=g.style;if(g.id){if(0===g.id.indexOf(f.tn)){var C=g.nextSibling;C&&(C.getAttribute&&C.getAttribute("data-gapistub"))&&h.removeChild(C);A.cssText=""}}else g.id=f.tn+q(f.Gb);n.height&&(A.height=n.height+"px");n.width&&(A.width=n.width+"px");A.display||(A.display="inline-block");(0,_.Xc)(g);var F=":"+f.Gb;":plus"==F&&(a.le&&a.le.action)&&(F+="_"+a.le.action);var h={},A=f.zh[0],C=n.callback,I=f.zh[1];if(I)var K=C||(0,_.x)(),C=function(a){var c=I(a);if(c){var f=a.href||_.s;if(U&&
window._gat)try{var g=window._gat._getTrackerByName("~0");g&&"UA-XXXXX-X"!=g._getAccount()?g._trackSocial("Google",c,f):window._gaq&&window._gaq.push(["_trackSocial","Google",c,f])}catch(h){}if(ka&&window.dataLayer)try{window.dataLayer.push({event:"social",socialNetwork:"Google",socialAction:c,socialTarget:f})}catch(l){}}K(a)};A&&C&&(h[A]=C);A=f.Qh;for(C=A.length-1;0<=C;--C){var ja=A[C],S=n[ja];S&&(h[ja]=S)}A={};for(ja in a.le)a.le[ja]!=_.s&&(A[ja]=a.le[ja]);ja={container:g.id,renderData:a.Yr,style:"inline",
height:n.height,width:n.width};l(ja);f.ne&&(c[2]=ja,c[3]=A,c[4]=h,f.ne("i",c),a.Rg=c[1]);ja=function(a){var c=w.apply(_.s,[F].concat([].slice.call(arguments,0)));if(n.onready){var f=_.u,g=function(){f||(f=_.r,n.onready.call(_.s))};c.da("ready",g);c.da("renderstart",g)}(0,_.he)(c);return c}(ja,A,h);v(ja,g);t(f,ja,a.xp);c[5]=ja;f.ne&&f.ne("e",c)};return f}function q(a){var c=(0,_.wa)();window.Object.prototype.hasOwnProperty.call(c,a)||(c[a]=0);var f=c[a];c[a]=f+1;return f}function t(a,c,f){function g(){t||
(t=_.r,h(),f&&(0,_.Td)("wrrt",l,n),(0,_.Td)("wrri",l,n))}function h(){q||(q=_.r,c.Z(),f&&(0,_.Td)("wrdt",l,n),(0,_.Td)("wrdi",l,n))}var l=a.Gb,n=(0,window.String)(a.Lj),q=_.u;c.da("renderstart",h);var t=_.u;c.da("ready",g);_.R.R("widget-interactive-"+c.id,g);_.R.R("widget-csi-tick-"+c.id,function(a,c,f){"wdc"===a||"wci"===a?(0,_.Td)("wdc",l,n,f):"wje0"===a||"wji_"===a?(0,_.Td)("wje0",l,n,f):"wje1"===a||"wji"===a?(0,_.Td)("wje1",l,n,f):"wh0"==a?((0,_.Ud)(l,n).wh0=f||(0,_.Ad)(),(0,_.Bd)("wh0",l,n)):
"wh1"==a&&((0,_.Ud)(l,n).wh1=f||(0,_.Ad)(),(0,_.Bd)("wh1",l,n))})}function v(a,c){function f(g){g=g||a;var h=(0,_.Fc)(a,g.width);h&&c.style.width!=h.nd&&(c.style.width=h.nd);if((g=(0,_.Fc)(a,g.height))&&c.style.height!=g.nd)c.style.height=g.nd}a.da("ready",f);a.da("renderstart",f);a.da("resize",f)}function w(a,c,f,g){return _.T.open(a,c,f,g)}function A(a,c){for(var f in Ca)if(Ca.hasOwnProperty(f)){var g=Ca[f][1];g&&!c.hasOwnProperty(g)&&(c[g]=a[g])}return c}function C(c,f){var g={},h;for(h in c)c.hasOwnProperty(h)&&
(g[c[h][1]||h]=(c[h]&&c[h][0]||a)(f[h],f,S));return g}function M(a){if(a=a.Pr)for(var c=0;c<a.length;c++)(new window.Image).src=a[c]}function I(a){function c(){"onload"===K&&g.go()}var f=n(a);M(f);(0,_.dc)(f.Gb,function(a){var c=a.userParams,g=a.iframeNode;if((g=g&&g.parentNode)&&1===g.nodeType){g.removeAttribute("data-gwattr");var h=C(f.Ba,c);f.Dm.push({element:g,Ba:h,le:A(h,C(f.Kr,c)),Rg:3,xp:!!c["data-onload"],Yr:a})}a=f.Dm;for(c=f.cj;0<a.length;)c(a.shift())});_.Cd[f.Gb]=_.r;var g={H:function(a,
c){var g=c||{};g.type=f.Gb;var h=g.type;delete g.type;var l=("string"===typeof a?window.document.getElementById(a):a)||_.p,n={},q;for(q in g)(0,_.Ra)(g,q)&&(n[q.toLowerCase()]=g[q]);n.rd=1;(0,_.Id)(h,l,n,[],0)},go:function(a){(0,_.yd)(a,f.Gb)},b:function(){var a=(0,_.wa)(),c;for(c in a)delete a[c]}};(0,_.vd)(f.Gb)||(0,_.wd)(c,c);return g}var F=["div"],K="onload",U=_.r,ka=_.r,S=_.s;(function(){S=(0,_.O)();(0,_.O)("gwidget");var a=c("parsetags");K="explicit"===a||"onload"===a?a:K;a=c("google_analytics");
"undefined"!==typeof a&&(U=!!a);a=c("data_layer");"undefined"!==typeof a&&(ka=!!a)})();var Ca=function(){var a={};a.width=[f(450)];a.height=[f(24)];a.callback=[g];a.onready=[g];a.lang=[h,"hl"];a.iloader=[function(){return _.xa.ILI},"iloader"];return a}();return{Ea:function(a){return I(a)}}}();

_.zt=(window.gapi||{}).load;
_.T.rj("bubble",function(a){(0,_.zt)("iframes-styles-bubble",a)});
_.T.rj("slide-menu",function(a){(0,_.zt)("iframes-styles-slide-menu",a)});

_.vv=function(a,c,f){a=(0,_.qd)(a);c=(0,_.dd)(c);if(""!=a){if("inline"==a||"only"==a)return a=450,f.width&&(a=120<f.width?f.width:120),{width:a,height:_.ed[c]["false"].height};if("bubble"!=a){if("none"==a)return _.ed[c]["false"];if("pp"==a)return _.wv}}return _.ed[c]["true"]};_.wv={width:180,height:35};
_.Xa=_.$a=function(){var a={"0":"plusone"},c=(0,_.O)("iframes/plusone/preloadUrl");c&&(a[8]=c);(0,_.ud)(_.id);a[1]=_.id;a[2]={width:[function(a,c){return c.annotation?(0,_.vv)(c.annotation,c.size,c).width:_.ed[(0,_.dd)(c.size)][(0,_.fd)(c.count,c.size)].width}],height:[function(a,c){return c.annotation?(0,_.vv)(c.annotation,c.size,c).height:_.ed[(0,_.dd)(c.size)][(0,_.fd)(c.count,c.size)].height}]};a[3]=["onPlusOne",function(a){return"on"==a.state?"+1":_.s}];a[4]=["div","button"];a[6]=["onstartinteraction", "onendinteraction","onpopup"];return _.ne.Ea(a)}();
(0,_.P)("gapi.plusone.render",_.$a.H);(0,_.P)("gapi.plusone.go",_.$a.go);(0,_.P)("googleapisv0.plusone.render",_.Xa.H);(0,_.P)("googleapisv0.plusone.go",_.Xa.go);
});

// Copyright 2002-2013 Google Inc.
